/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProxiesRouteImport } from './routes/proxies'
import { Route as RunRouteImport } from './routes/run'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RunIndexRouteImport } from './routes/run.index'
import { Route as RunIdRouteImport } from './routes/run.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxiesRoute = ProxiesRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RunIndexRoute = RunIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunRoute,
} as any)
const RunIdRoute = RunIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RunRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proxies': typeof ProxiesRoute
  '/run': typeof RunRouteWithChildren
  '/settings': typeof SettingsRoute
  '/run/$id': typeof RunIdRoute
  '/run/': typeof RunIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proxies': typeof ProxiesRoute
  '/settings': typeof SettingsRoute
  '/run/$id': typeof RunIdRoute
  '/run': typeof RunIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proxies': typeof ProxiesRoute
  '/run': typeof RunRouteWithChildren
  '/settings': typeof SettingsRoute
  '/run/$id': typeof RunIdRoute
  '/run/': typeof RunIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/proxies' | '/run' | '/settings' | '/run/$id' | '/run/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/proxies' | '/settings' | '/run/$id' | '/run'
  id:
    '__root__' | '/' | '/proxies' | '/run' | '/settings' | '/run/$id' | '/run/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProxiesRoute: typeof ProxiesRoute
  RunRoute: typeof RunRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxies': {
      id: '/proxies'
      path: '/proxies'
      fullPath: '/proxies'
      preLoaderRoute: typeof ProxiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/': {
      id: '/run/'
      path: '/'
      fullPath: '/run/'
      preLoaderRoute: typeof RunIndexRouteImport
      parentRoute: typeof RunRoute
    }
    '/run/$id': {
      id: '/run/$id'
      path: '/$id'
      fullPath: '/run/$id'
      preLoaderRoute: typeof RunIdRouteImport
      parentRoute: typeof RunRoute
    }
  }
}

interface RunRouteChildren {
  RunIdRoute: typeof RunIdRoute
  RunIndexRoute: typeof RunIndexRoute
}

const RunRouteChildren: RunRouteChildren = {
  RunIdRoute: RunIdRoute,
  RunIndexRoute: RunIndexRoute,
}

const RunRouteWithChildren = RunRoute._addFileChildren(RunRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProxiesRoute: ProxiesRoute,
  RunRoute: RunRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
